server:
  shutdown: graceful
  port: 8081

spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      username: root
      password: root
      authentication-database: admin
      auto-index-creation: true
      database: ticket_db

debezium:
  replication:
    name: rs0
    primary:
      hosts: 127.0.0.1
      port: 27017
      username: root
      password: root

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongo

debezium:
  replication:
    primary:
      hosts: mongo